<Project>
	<PropertyGroup>
		<Version>0.3.2</Version>
		<Authors>MvvmAIO, Skymly, wys0610</Authors>
		<Company>MvvmAIO</Company>
		<Copyright>Copyright © MvvmAIO</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/MvvmAIO/MvvmAIO.Markup</PackageProjectUrl>
		<RepositoryUrl>https://github.com/MvvmAIO/MvvmAIO.Markup.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsPackable)' == 'true'">
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsPackable)' == 'true'">
		<PackageReference Include="Microsoft.SourceLink.GitHub">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
