<Project>
	<PropertyGroup>
		<Version>0.1.2</Version>
		<Authors>MvvmAIO, Skymly, wys0610</Authors>
		<Company>MvvmAIO</Company>
		<Copyright>Copyright © MvvmAIO</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/MvvmAIO/MvvmAIO.Markup</PackageProjectUrl>
		<RepositoryUrl>https://github.com/MvvmAIO/MvvmAIO.Markup.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>
</Project>
