<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net461;net462;net472;net48;net481;net6.0-windows;net7.0-windows;net8.0-windows;net9.0-windows;net10.0-windows;</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<LangVersion>14.0</LangVersion>
		<RootNamespace>MvvmAIO.Markup</RootNamespace>
		<DefineConstants>$(DefineConstants);WPF</DefineConstants>
		<PolyArgumentExceptions>true</PolyArgumentExceptions>
		<IsPackable>true</IsPackable>
		<PackageId>MvvmAIO.Markup.WPF</PackageId>
		<Description>Markup helpers and utilities for WPF in the MvvmAIO stack.</Description>
		<PackageTags>wpf;mvvm;markup;MvvmAIO;XAML</PackageTags>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Polyfill" Version="10.5.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<Import Project="..\MvvmAIO.Markup.Shared\MvvmAIO.Markup.Shared.projitems" Label="Shared" />

</Project>
