<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>MvvmAIO.Markup</RootNamespace>
		<DefineConstants>$(DefineConstants);Avalonia</DefineConstants>
		<LangVersion>14.0</LangVersion>
		<IsPackable>true</IsPackable>
		<PackageId>MvvmAIO.Markup.Avalonia</PackageId>
		<Description>XAML markup extensions for strongly typed literals in Avalonia.</Description>
		<PackageTags>avalonia;mvvm;markup;MvvmAIO;XAML</PackageTags>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Polyfill">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<Import Project="..\MvvmAIO.Markup.Shared\MvvmAIO.Markup.Shared.projitems" Label="Shared" />

</Project>
