<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net462;net8.0-windows</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<UseWPF>true</UseWPF>
		<LangVersion>14.0</LangVersion>
		<RootNamespace>Samples</RootNamespace>
		<OutputType>WinExe</OutputType>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="CommunityToolkit.Mvvm" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MvvmAIO.Markup.WPF\MvvmAIO.Markup.WPF.csproj" />
	</ItemGroup>

</Project>
